image: Visual Studio 2019
skip_commits:
  message: /docs|Merge pull request.*/
install:
  - choco install googlechrome --ignorechecksum
build_script:
- ps: >-
    dotnet build --configuration Release

    dotnet test --configuration Release --no-build --no-restore --filter Category!=Integration
on_failure:
  - ps: Get-ChildItem *.received.* -recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
test: off