image: Visual Studio 2022
init:
  - npx playwright install
install:
  - ps: |
      $certfile = Join-Path -Path (Resolve-Path ".").Path -ChildPath "cert.pfx"
      $certPwd = "somepassword"
      Remove-Item $certfile -ErrorAction SilentlyContinue
      dotnet dev-certs https --clean
      dotnet dev-certs https --export-path=$certfile --password=$certPwd --verbose
      $cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2($certfile, $certPwd, "PersistKeySet")
      $rootStore = New-Object System.Security.Cryptography.X509Certificates.X509Store("Root", "LocalMachine");
      $rootStore.Open("ReadWrite")
      $rootStore.Add($cert)
      $rootStore.Close()
build_script:
- pwsh: |
    Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile "./dotnet-install.ps1"
    ./dotnet-install.ps1 -JSonFile global.json -Architecture x64 -InstallDir 'C:\Program Files\dotnet'
- dotnet build --configuration Release
- dotnet test --configuration Release --no-build --no-restore
on_failure:
  - ps: Get-ChildItem *.received.* -recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
test: off